// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi1HeMcAbrXkC-SGRUpU9CiydZ6FBe6tM',
    appId: '1:432339124188:web:fb02c508a1c28b37725919',
    messagingSenderId: '432339124188',
    projectId: 'flutter-dodo',
    authDomain: 'flutter-dodo.firebaseapp.com',
    storageBucket: 'flutter-dodo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6jMMR-teNiZoFV31dxaE94BWs47QUdmk',
    appId: '1:432339124188:android:2c5755797ae92889725919',
    messagingSenderId: '432339124188',
    projectId: 'flutter-dodo',
    storageBucket: 'flutter-dodo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgwk1taiEyr0s69a7cirf3YxI7J0bdbKA',
    appId: '1:432339124188:ios:f329ca45219a87ee725919',
    messagingSenderId: '432339124188',
    projectId: 'flutter-dodo',
    storageBucket: 'flutter-dodo.appspot.com',
    iosClientId: '432339124188-a6ipgj86traijjlis1o2scmnt1537dk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.habbitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgwk1taiEyr0s69a7cirf3YxI7J0bdbKA',
    appId: '1:432339124188:ios:f86c39317021508a725919',
    messagingSenderId: '432339124188',
    projectId: 'flutter-dodo',
    storageBucket: 'flutter-dodo.appspot.com',
    iosClientId: '432339124188-9cmpjc9juen7v9u9edvq91etutcgb20q.apps.googleusercontent.com',
    iosBundleId: 'habittracker.habitTracker',
  );
}
