# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        ref: "feature/gh-actions"
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.19.5
    - run: flutter --version
    - name: pub get 
      run: flutter pub get
    - name: flutter build
      run: flutter build apk --split-per-abi --dart-define=build=test --release

